#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成完整的180篇审计案例分类结果"""
import json, os

# 读取导出的数据
with open(r'D:\openclaw-workspace\for_classification.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# 预定义的分类数据（根据已阅读的所有内容）
# 格式: id -> {scene, findings, recommendations, regulations, keywords}
CLASSIFICATIONS = {
    1: {"scene": "政策落实审计", "findings": [], "recommendations": ["完善补助资金审核流程", "加强申报材料审核把关"], "regulations": ["藏文旅发〔2026〕27号", "林政办发〔2018〕154号"], "keywords": ["冬游西藏", "补助资金审核", "旅游补贴"]},
    2: {"scene": "金融审计", "findings": ["总部统筹的专项审计存在资源结构失衡、权责边界模糊问题", "审计重点执行刚性与实际情况不匹配", "集中排查数据核实刚性与实际情况不匹配"], "recommendations": ["优化审计资源配置", "建立柔性审计重点调整机制"], "regulations": [], "keywords": ["总部统筹", "专项审计", "商业银行", "资源配置"]},
    3: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《关于"人工智能+交通运输"的实施意见》"], "keywords": ["人工智能", "交通运输", "科技创新", "十五五"]},
    4: {"scene": "社保民生审计", "findings": ["医保违规行为隐蔽化", "信息壁垒突出", "审计效能不足"], "recommendations": ["构建多维度穿透审计框架", "强化数据赋能", "加强人才队伍建设", "完善数据安全保障制度"], "regulations": [], "keywords": ["人工智能", "穿透式审计", "医保审计", "社保基金"]},
    5: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["数据要素", "一体化市场", "数字中国", "数据治理"]},
    6: {"scene": "信息系统审计", "findings": ["智慧审计落地面临制度适配障碍", "技术应用碎片化", "数据资源孤岛化"], "recommendations": ["推进制度适配性改革", "构建统一的智慧审计平台"], "regulations": [], "keywords": ["智慧审计", "数字化转型", "制度适配", "企业审计"]},
    7: {"scene": "信息系统审计", "findings": ["水利关键信息基础设施网络安全风险显著增加", "智慧水利建设与安全防护存在脱节"], "recommendations": ["加强关键信息基础设施安全审计", "完善智慧水利安全防护体系"], "regulations": ["《网络安全法》", "《关键信息基础设施安全保护条例》"], "keywords": ["关键信息基础设施", "水利", "网络安全", "智慧水利"]},
    8: {"scene": "信息系统审计", "findings": ["数智化审计伴生数据安全风险", "算法偏见与决策黑箱", "模型幻觉等生成式风险"], "recommendations": ["构建云边端韧性风险治理机制", "实施制度、技术、人才与组织四维联动创新"], "regulations": [], "keywords": ["云边端", "智慧审计", "韧性治理", "风险防控"]},
    9: {"scene": "信息系统审计", "findings": ["A股市场舞弊行为日益隐蔽化、复杂化", "传统有监督模型对新型舞弊识别存在盲区"], "recommendations": ["运用大语言模型增强聚类分析识别舞弊"], "regulations": [], "keywords": ["大模型", "舞弊识别", "A股", "机器学习"]},
    10: {"scene": "教科文卫审计", "findings": ["高校审计数据采集不健全", "模型落地应用困难"], "recommendations": ["实施一把手牵头推进机制", "建立问题导向大数据审计模型"], "regulations": [], "keywords": ["高校审计", "大数据审计模型", "内部审计", "数据采集"]},
    11: {"scene": "信息系统审计", "findings": ["软硬件适配难题与算力瓶颈", "跨系统数据对接困难"], "recommendations": ["构建领域大模型+知识内嵌的审计一体机架构"], "regulations": [], "keywords": ["审计一体机", "大模型", "知识内嵌", "智能化审计"]},
    12: {"scene": "信息系统审计", "findings": ["基层审计机关推进智慧审计面临挑战"], "recommendations": ["加强科技强审", "推动现代信息技术与审计业务深度融合"], "regulations": [], "keywords": ["基层审计", "智慧审计", "科技强审", "成华区"]},
    13: {"scene": "教科文卫审计", "findings": ["公立医院面临公益属性与运营效率等多重矛盾", "传统财务收支审计难以穿透医疗业务复杂性"], "recommendations": ["构建研究先行、数据驱动的双轮驱动策略", "多源数据融合构建复合审计监督体系"], "regulations": [], "keywords": ["公立医院审计", "数据融合", "新疆审计厅", "复合审计体系"]},
    14: {"scene": "国企审计", "findings": [], "recommendations": ["构建数据驱动的1+3智慧审计监督模式", "创新双循环与双主审监督模式", "搭建培训认证体系培育数智化人才"], "regulations": [], "keywords": ["东风汽车", "智慧审计", "数据驱动", "央企审计", "内部审计"]},
    15: {"scene": "其他审计", "findings": ["技术应用碎片化", "数据资源孤岛化", "人才培养模式滞后"], "recommendations": ["推动审计人才培养适应性变革"], "regulations": [], "keywords": ["数智化转型", "审计人才培养", "新质生产力"]},
    16: {"scene": "教科文卫审计", "findings": ["高校审计整改主要依托传统方式推进", "成效参差不齐"], "recommendations": ["构建审计整改信息平台", "利用信息技术提升整改质效"], "regulations": [], "keywords": ["审计整改", "信息平台", "高校审计", "内部审计"]},
    17: {"scene": "信息系统审计", "findings": ["人社关键信息基础设施制度体系建设存在短板"], "recommendations": ["加强人社行业关键信息基础设施安全审计"], "regulations": [], "keywords": ["关键信息基础设施", "人社", "网络安全", "审计视角"]},
    18: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《关于深入实施"人工智能+"行动的意见》"], "keywords": ["人工智能+", "政策解读", "审计视角"]},
    19: {"scene": "信息系统审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["智慧审计", "研究综述", "审计信息化"]},
    20: {"scene": "工程审计", "findings": ["招标投标领域存在违法违规行为"], "recommendations": ["构建招标投标审计监督体系", "运用大数据技术识别违法违规行为"], "regulations": ["《招标投标法》", "《招标投标法实施条例》"], "keywords": ["招标投标", "审计监督", "大数据", "政府投资项目"]},
    21: {"scene": "信息系统审计", "findings": ["政务信息化存在系统重复建设", "资金绩效不佳", "数据安全隐患"], "recommendations": ["从政策落实、资金管理使用、项目建设、运营效能、网络安全五维度构建审计监督体系"], "regulations": [], "keywords": ["信息化建设审计", "政务信息化", "政府部门", "网络安全"]},
    22: {"scene": "信息系统审计", "findings": ["数据资产权属追溯难", "价值评估难", "合规验证难"], "recommendations": ["构建形成-确权-估值-入表-审计全周期协同治理框架"], "regulations": [], "keywords": ["数据资产", "数据确权", "全周期治理", "审计难点"]},
    23: {"scene": "内部审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["数智化", "内部审计", "CiteSpace", "研究热点"]},
    24: {"scene": "其他审计", "findings": [], "recommendations": ["数智技术与管理审计课程教学深度融合"], "regulations": [], "keywords": ["数智技术", "审计教学", "课程改革", "人才培养"]},
    25: {"scene": "内部审计", "findings": ["内部审计立项精准性不足"], "recommendations": ["运用数智技术赋能审计立项精准化"], "regulations": [], "keywords": ["内部审计", "立项精准化", "数智赋能", "运行机制"]},
    26: {"scene": "信息系统审计", "findings": [], "recommendations": ["关注公路水路运输关键信息基础设施建设审计"], "regulations": [], "keywords": ["关键信息基础设施", "公路水路运输", "审计要点"]},
    27: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["欧洲审计院", "AI战略", "审计智能化", "国际比较"]},
    28: {"scene": "国企审计", "findings": ["交通投资企业业务多元、系统分散", "审计资源有限"], "recommendations": ["建设流程与数智双轮驱动的审计数字化架构", "打通多源数据壁垒"], "regulations": [], "keywords": ["湖北交投", "审计数字化", "交通投资", "内部审计"]},
    29: {"scene": "信息系统审计", "findings": ["审计数据共享和协同利用不足"], "recommendations": ["构建审计数据底座", "强化数据共享和协同利用"], "regulations": [], "keywords": ["数据底座", "审计数据", "监督共同体", "协同治理"]},
    30: {"scene": "国企审计", "findings": [], "recommendations": ["以审计赋能科技创新", "以数智护航自立自强"], "regulations": [], "keywords": ["矿冶集团", "科技创新", "央企审计", "数智化"]},
    31: {"scene": "信息系统审计", "findings": [], "recommendations": ["加强卫健行业关键信息基础设施建设审计"], "regulations": [], "keywords": ["关键信息基础设施", "卫健行业", "数字健康", "审计"]},
    32: {"scene": "信息系统审计", "findings": [], "recommendations": ["聚焦关键信息基础设施建设安全审计", "提升应急处置能力"], "regulations": [], "keywords": ["关键信息基础设施", "应急管理", "安全审计", "应急处置"]},
    33: {"scene": "国企审计", "findings": ["航空企业各系统数据标准不一、互联互通不足", "风险预警与报告机制滞后"], "recommendations": ["推动内部审计和风险管理数字化转型"], "regulations": [], "keywords": ["航空企业", "内部审计", "风险管理", "数字化转型"]},
    34: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["宏观经济", "GDP", "数据解读", "2025年"]},
    35: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["国家审计", "研究进展", "文献综述", "2025年"]},
    36: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["财政健康", "系统论", "财政管理", "审计公开课"]},
    37: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《关于加快场景培育和开放推动新场景大规模应用的实施意见》"], "keywords": ["场景培育", "政策解读", "科技创新"]},
    38: {"scene": "教科文卫审计", "findings": ["基础研究财政重视不够", "基础研究基地有短板"], "recommendations": ["加强基础研究资金审计", "关注科技创新政策落实"], "regulations": [], "keywords": ["基础研究", "上海", "科技创新审计", "政策布局"]},
    39: {"scene": "其他审计", "findings": [], "recommendations": ["运用七种思维能力科学谋划十五五审计工作"], "regulations": [], "keywords": ["七种思维", "十五五", "审计谋划", "审计方法论"]},
    40: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["审计史", "魏晋南北朝", "比部", "审计知识体系"]},
    41: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["正确政绩观", "十五五", "卷首语"]},
    42: {"scene": "其他审计", "findings": [], "recommendations": ["以请示报告为抓手提升审计体制运转效能"], "regulations": [], "keywords": ["请示报告", "审计体制", "济南", "审计管理"]},
    43: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["高质量审计", "审计监督", "经济社会高质量发展"]},
    44: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《会计法》"], "keywords": ["会计职业禁止", "制度研究", "会计违法"]},
    45: {"scene": "其他审计", "findings": [], "recommendations": ["构建法律+技术+管理三位一体全流程阻断机制"], "regulations": [], "keywords": ["深度合成", "犯罪产业链", "AIGC", "网络安全"]},
    46: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["投资", "高质量发展", "十五五", "宏观经济"]},
    47: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["新质生产力", "因地制宜", "卷首语"]},
    48: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["国外审计", "审计协作", "国际比较", "国家治理"]},
    49: {"scene": "预算执行审计", "findings": ["地方政府存在借新还旧化解存量债务", "盲目举债上新项目", "违规举债手法隐蔽"], "recommendations": ["关注地方政府债务管理长效机制", "加强对隐性债务的审计监督"], "regulations": ["《预算法》"], "keywords": ["地方政府债务", "违规举债", "隐性债务", "审计思路"]},
    50: {"scene": "信息系统审计", "findings": ["动态审计预警面临非结构化数据处理难度大", "政策变化适应性不足", "预警模型单一"], "recommendations": ["应用大语言模型优化审计数据采集和风险识别", "建立持续优化的预警模型"], "regulations": [], "keywords": ["大语言模型", "动态审计预警", "风险识别", "内部审计"]},
    51: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《中国注册会计师独立性准则第1号》"], "keywords": ["外部质量复核", "独立性风险", "注册会计师", "社会审计"]},
    52: {"scene": "其他审计", "findings": [], "recommendations": ["以系统思维提炼高质量审计建议"], "regulations": [], "keywords": ["审计建议", "系统思维", "研究型审计", "审计方法"]},
    53: {"scene": "政策落实审计", "findings": ["宏观政策取向不一致", "各部门政策目标错位"], "recommendations": ["开展宏观政策取向一致性审计"], "regulations": [], "keywords": ["宏观政策", "政策一致性", "审计探析", "宏观经济治理"]},
    54: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["财政政策", "宏观治理", "十五五", "经济工作"]},
    55: {"scene": "其他审计", "findings": ["风腐交织问题严重", "查风查腐分离"], "recommendations": ["推进风腐同查同治", "以审计监督切入权力运行逻辑"], "regulations": [], "keywords": ["风腐同查", "审计反腐", "作风建设", "内在机理"]},
    56: {"scene": "金融审计", "findings": ["地方AMC面临监管困境"], "recommendations": [], "regulations": ["《地方资产管理公司监督管理暂行办法》"], "keywords": ["地方AMC", "资产管理", "金融监管", "审计视角"]},
    57: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["巴西审计法院", "战略规划", "国际审计", "审计管理"]},
    58: {"scene": "内部审计", "findings": ["总审计师制度存在独立性不足等问题"], "recommendations": ["优化总审计师制度建设", "推动审计从合规监督向价值创造转型"], "regulations": [], "keywords": ["总审计师", "合规监督", "价值创造", "企业治理"]},
    59: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["氢能产业", "审计关注点", "产业发展", "新能源"]},
    60: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["陕甘宁边区", "边币发行", "抗战金融", "历史研究"]},
    61: {"scene": "其他审计", "findings": [], "recommendations": ["运用新技术赋能审计监督推进反腐治乱"], "regulations": [], "keywords": ["新技术", "审计监督", "反腐治乱", "科技强审"]},
    62: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["本期关注", "期刊目录", "内容导读"]},
    63: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["正确政绩观", "中国式现代化", "卷首语"]},
    64: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["欧盟审计院", "战略规划", "国际审计", "审计管理"]},
    65: {"scene": "资源环境审计", "findings": [], "recommendations": ["构建气候变化适应审计实施框架"], "regulations": [], "keywords": ["气候变化", "适应审计", "环境审计", "实施框架"]},
    66: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["法国审计法院", "司法型审计", "国际比较", "审计制度"]},
    67: {"scene": "预算执行审计", "findings": [], "recommendations": ["拓展审计监督覆盖面", "做到资金监督全过程"], "regulations": ["《党政机关厉行节约反对浪费条例》"], "keywords": ["厉行节约", "审计监督", "预算执行", "财政资金"]},
    68: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["澳大利亚审计署", "战略规划", "国际审计", "审计管理"]},
    69: {"scene": "工程审计", "findings": ["建筑企业面临宏观经济风险、市场竞争、投资不足"], "recommendations": ["开展研究型审计贯穿项目全周期全流程全要素"], "regulations": [], "keywords": ["建筑企业", "研究型审计", "内部审计", "工程审计"]},
    70: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《会计师事务所反洗钱工作管理办法》", "《反洗钱法》"], "keywords": ["反洗钱", "会计师事务所", "政策解读", "合规管理"]},
    71: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《中华苏维埃共和国中央政府执行委员会审计条例》"], "keywords": ["苏区审计", "审计史", "审计立法", "中央苏区"]},
    72: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["英国审计署", "战略规划", "国际审计", "审计管理"]},
    73: {"scene": "国企审计", "findings": ["融资性贸易虚增收入手法隐蔽", "关联链条复杂", "传统审计手段难以精准识别"], "recommendations": ["构建数据采集+多维验证+疑点核实的数据审计框架"], "regulations": [], "keywords": ["融资性贸易", "虚增收入", "国企审计", "数据审计"]},
    74: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["财会管理", "政策梳理", "财会监督", "趋势分析"]},
    75: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["湖南审计", "三高四新", "审计厅长专访", "审计管理"]},
    76: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《晋冀鲁豫边区岁入岁出审计规程》"], "keywords": ["革命根据地", "审计史", "晋冀鲁豫", "审计制度"]},
    77: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["马克思主义", "审计学科", "自主知识体系", "理论创新"]},
    78: {"scene": "其他审计", "findings": [], "recommendations": ["高质量谋划十五五时期审计工作"], "regulations": [], "keywords": ["十五五", "审计谋划", "枣庄审计", "审计管理"]},
    79: {"scene": "内部审计", "findings": ["企业重大战略投资项目存在投而难管、决策与执行脱节"], "recommendations": ["建立专职董事与内部审计协同赋能机制"], "regulations": [], "keywords": ["专职董事", "内部审计", "协同赋能", "公司治理"]},
    80: {"scene": "内部审计", "findings": ["部分企业内部审计独立性不强", "审计委员会形同虚设"], "recommendations": ["加快构建世界一流内部审计体系"], "regulations": [], "keywords": ["内部审计体系", "世界一流", "企业治理", "独立性"]},
    81: {"scene": "内部审计", "findings": [], "recommendations": ["加强内部审计对财政资金监管的作用"], "regulations": [], "keywords": ["内部审计", "财政资金监管", "作用机制", "优化路径"]},
    82: {"scene": "内部审计", "findings": [], "recommendations": ["构建内部审计助力一带一路建设的机制与路径"], "regulations": [], "keywords": ["一带一路", "内部审计", "央企", "国际化"]},
    83: {"scene": "内部审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["内部审计", "双重管理体制", "理论探讨"]},
    84: {"scene": "内部审计", "findings": ["内部审计时效性弱", "整改成效性差", "责任界定不清"], "recommendations": ["加强任中审计", "完善审计整改闭环"], "regulations": [], "keywords": ["内部审计", "质效提升", "短板分析", "企业审计"]},
    85: {"scene": "内部审计", "findings": ["国有信用评级公司审计面临力量薄弱、思维固化困局"], "recommendations": ["加快人工智能转型发展", "以数智化赋能破解审计困局"], "regulations": [], "keywords": ["信用评级", "内部审计", "数智化转型", "国企"]},
    86: {"scene": "内部审计", "findings": ["国企审计整改责任落实不到位", "措施流于形式", "成果运用不充分"], "recommendations": ["构建审计整改闭环枢纽机制"], "regulations": ["《审计署关于内部审计工作的规定》", "《关于建立健全审计查出问题整改长效机制的意见》"], "keywords": ["审计整改", "闭环枢纽", "国企", "内部审计"]},
    87: {"scene": "国企审计", "findings": ["电力集团管理链条长、层级复杂"], "recommendations": ["构建穿透式监管视角下的风险内控一体化管理体系"], "regulations": [], "keywords": ["穿透式监管", "风险内控", "电力行业", "国企审计"]},
    88: {"scene": "内部审计", "findings": ["铁路货运运价项目数量激增、管理复杂"], "recommendations": ["构建全流程运价审计模式", "内部审计赋能运价精准化治理"], "regulations": [], "keywords": ["铁路货运", "内部审计", "运价管理", "价值创造"]},
    89: {"scene": "农业农村审计", "findings": ["乡村产业融合发展存在发展基础、融合质效、要素保障、项目管理四方面短板"], "recommendations": ["从政策落实、机制运转、资金绩效、项目管理四方面开展审计"], "regulations": [], "keywords": ["乡村产业", "融合发展", "乡村振兴", "审计研究"]},
    90: {"scene": "农业农村审计", "findings": [], "recommendations": ["关注产业集群项目审计重点"], "regulations": [], "keywords": ["农业产业集群", "审计重点", "乡村振兴", "专项资金"]},
    91: {"scene": "资源环境审计", "findings": ["农村生活污水治理存在乱倒乱排等问题"], "recommendations": ["加强农村生活污水治理审计监督"], "regulations": [], "keywords": ["农村污水", "人居环境", "资源环境审计", "乡村生态"]},
    92: {"scene": "教科文卫审计", "findings": ["农村义务教育营养餐政策执行存在餐费收取、资金使用、供餐管理等问题"], "recommendations": ["建立跨部门协同工作机制", "补齐监管薄弱环节", "确保政策不落一人"], "regulations": [], "keywords": ["农村义务教育", "营养餐", "审计调查", "教科文卫"]},
    93: {"scene": "国企审计", "findings": ["区属国企在资产运营、劳动用工、工程管理、合作经营等方面存在风险"], "recommendations": ["从裁决类法律文书中挖掘审计线索"], "regulations": [], "keywords": ["法律文书", "审计线索", "区属国企", "专项审计"]},
    94: {"scene": "国企审计", "findings": ["国企私募基金内部审计面临审计力量薄弱、思维固化、技术滞后困局"], "recommendations": ["以数智化赋能破解私募基金内部审计困局"], "regulations": [], "keywords": ["私募基金", "国企审计", "数智化", "内部审计"]},
    95: {"scene": "国企审计", "findings": [], "recommendations": ["发挥内部审计助力国企深化改革的作用"], "regulations": [], "keywords": ["国企改革", "内部审计", "深化改革", "深圳投控"]},
    96: {"scene": "国企审计", "findings": ["央企四类金融业务存在复杂股权结构", "通过关联交易套取收益", "偏离服务实体经济初衷"], "recommendations": ["加强中央企业四类金融业务审计监督"], "regulations": [], "keywords": ["央企金融业务", "审计监督", "产融结合", "风险防范"]},
    97: {"scene": "国企审计", "findings": [], "recommendations": ["转变内部审计定位", "锚定组织战略", "拥抱科技", "配齐建强专业化人才队伍"], "regulations": [], "keywords": ["国企内部审计", "高质量发展", "S集团", "战略定位"]},
    98: {"scene": "国企审计", "findings": ["政府职能部门监管不到位", "国企改革措施落实不到位", "国有资本布局不合理"], "recommendations": ["健全公司治理机制", "建立主业动态调整机制"], "regulations": [], "keywords": ["国企改革", "审计策略", "省属国企", "改革审计"]},
    99: {"scene": "国企审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["国企改革", "政策梳理", "审计重点", "改革审计"]},
    100: {"scene": "国企审计", "findings": ["国企主责主业定位不准", "偏离核心业务"], "recommendations": ["以问题风险为导向开展主责主业审计"], "regulations": [], "keywords": ["国企", "主责主业", "审计重点", "国资监管"]},
    101: {"scene": "国企审计", "findings": ["省属企业改革发展和风险防范存在不足"], "recommendations": [], "regulations": [], "keywords": ["国资国企改革", "浙江审计", "专项审计调查", "国企审计"]},
    102: {"scene": "国企审计", "findings": ["地方国企在公益性职能与市场化运营双重使命下成为财政风险滋生和传导关键环节"], "recommendations": ["构建数据采集-疑点识别-责任追溯全流程审计解决方案"], "regulations": [], "keywords": ["地方国企", "财政风险", "审计策略", "风险防控"]},
    103: {"scene": "国企审计", "findings": ["央企研发投入产出存在数据真实性、产出效率等问题"], "recommendations": ["关注研发投入数据真实性", "关注研发产出效率和效果"], "regulations": [], "keywords": ["央企", "研发投入", "审计对策", "国企审计"]},
    104: {"scene": "国企审计", "findings": [], "recommendations": ["更好践行国有资本运营公司使命担当"], "regulations": [], "keywords": ["国有资本运营", "中国国新", "十五五", "国企使命"]},
    105: {"scene": "国企审计", "findings": ["国企境外投资面临结构失衡、监管缺失及资产虚胖等痛点"], "recommendations": ["构建链式穿透与数智赋能的审计新体系", "审计职能从查错纠弊向增值导向转型"], "regulations": [], "keywords": ["境外投资", "国企审计", "链式穿透", "数智赋能"]},
    106: {"scene": "国企审计", "findings": [], "recommendations": ["以新公司法为契机提升国企审计监督效能"], "regulations": ["《公司法》(2023修订)"], "keywords": ["新公司法", "国企审计", "审计委员会", "监督效能"]},
    107: {"scene": "国企审计", "findings": ["审计整改是国企内部审计的关键环节", "存在整改不到位问题"], "recommendations": ["构建审计整改3个1标准化管理体系"], "regulations": [], "keywords": ["审计整改", "国企", "标准化", "内部审计", "C公司"]},
    108: {"scene": "国企审计", "findings": ["概念验证中心国有资产绩效审计存在制度不适配问题"], "recommendations": ["构建以分类治理、权责统一、动态审计为核心的制度重构路径"], "regulations": [], "keywords": ["概念验证中心", "国有资产", "绩效审计", "指标体系"]},
    109: {"scene": "工程审计", "findings": ["两重建设项目存在资金管理和使用不规范问题"], "recommendations": ["关注两重建设项目安排的合规性和效益性"], "regulations": [], "keywords": ["两重建设", "项目审计", "超长期特别国债", "工程审计"]},
    110: {"scene": "工程审计", "findings": ["高校工程项目投资大、周期长、环节多、管理复杂"], "recommendations": ["构建数据驱动的高校工程审计监督体系", "应用BIM与智慧审计平台"], "regulations": [], "keywords": ["高校工程审计", "数据驱动", "BIM", "工程审计监督"]},
    111: {"scene": "工程审计", "findings": [], "recommendations": ["构建数据采集-智能处理-审计分析-结果输出的全流程工程结算审计智能化应用路径"], "regulations": [], "keywords": ["工程结算审计", "智能化", "数字化转型", "工程造价"]},
    112: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["两新政策", "消费增长", "卷首语"]},
    113: {"scene": "政策落实审计", "findings": ["两重两新政策存在监管不严、政策落实不到位、资金违规使用或长期闲置"], "recommendations": ["加强两重两新政策执行审计监督"], "regulations": [], "keywords": ["两重两新", "政策落实", "审计监督", "财政资金"]},
    114: {"scene": "政策落实审计", "findings": ["W市两新政策执行存在协同推进体系不完善等问题"], "recommendations": ["从审计视角提出解决政策执行问题的办法"], "regulations": [], "keywords": ["两新政策", "W市", "政策执行", "审计视角"]},
    115: {"scene": "政策落实审计", "findings": [], "recommendations": ["进一步优化两新政策完善扩大内需战略举措"], "regulations": [], "keywords": ["两新政策", "扩大内需", "设备更新", "以旧换新"]},
    116: {"scene": "教科文卫审计", "findings": ["医院经济合同管理存在困境与风险"], "recommendations": ["加强医院经济合同管理的内部审计举措"], "regulations": [], "keywords": ["医院", "经济合同管理", "内部审计", "风险防控"]},
    117: {"scene": "教科文卫审计", "findings": ["医院财务迎审环节存在不规范问题"], "recommendations": ["构建医院财务迎审工作规范化路径"], "regulations": [], "keywords": ["医院财务", "迎审工作", "规范化", "财务审计"]},
    118: {"scene": "教科文卫审计", "findings": [], "recommendations": ["实现审计监督与科技体制改革政策取向一致性"], "regulations": [], "keywords": ["科技体制改革", "审计监督", "政策一致性", "科技创新"]},
    119: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["审计制度", "审计文化", "内涵发展", "理论探讨"]},
    120: {"scene": "教科文卫审计", "findings": ["科技创新中心存在基础研究财政重视不够、技术创新平台建设不理想、未来产业布局同质化等问题"], "recommendations": ["关注科技创新中心建设中的审计重点"], "regulations": [], "keywords": ["科技创新中心", "审计关注", "基础研究", "成果转化"]},
    121: {"scene": "教科文卫审计", "findings": [], "recommendations": [], "regulations": ["《文化产业发展专项资金管理办法》"], "keywords": ["文化产业", "专项资金", "审计视角", "财政支持"]},
    122: {"scene": "教科文卫审计", "findings": ["高校内部审计面临定位与体系不周备、信息化程度低、审计力量薄弱等问题"], "recommendations": ["构建高校内部审计高质量发展的四梁八柱体系"], "regulations": [], "keywords": ["高校内部审计", "高质量发展", "四梁八柱", "治理体系"]},
    123: {"scene": "教科文卫审计", "findings": ["安徽高校审计发现高校治理逐步规范但仍有问题"], "recommendations": ["深化研究型审计护航高校高质量发展"], "regulations": [], "keywords": ["安徽高校", "研究型审计", "经济责任审计", "教科文卫审计"]},
    124: {"scene": "教科文卫审计", "findings": [], "recommendations": ["聚焦政策执行效果、资金分配使用、创新成果转化等方面开展审计"], "regulations": [], "keywords": ["科技创新", "审计关注", "成果转化", "政策执行"]},
    125: {"scene": "教科文卫审计", "findings": [], "recommendations": ["关注四链融合政策及科技成果转化审计"], "regulations": [], "keywords": ["四链融合", "陕西", "科技成果转化", "审计探析"]},
    126: {"scene": "教科文卫审计", "findings": ["A高校在政策执行、重大决策、预算收支、资产管理、内部控制等方面存在普遍性问题"], "recommendations": ["提出系统、可操作的高校治理完善路径"], "regulations": [], "keywords": ["高校审计", "问题根源", "治理优化", "A高校"]},
    127: {"scene": "教科文卫审计", "findings": ["高校科研经费审计与财会监督存在重复监督、信息隔阂问题"], "recommendations": ["构建内部审计监督与财会监督协同路径"], "regulations": [], "keywords": ["科研经费", "高校审计", "财会监督", "协同监督"]},
    128: {"scene": "社保民生审计", "findings": ["医药卫生领域存在垄断涨价、虚增环节、过度诊疗、违规收费等乱象"], "recommendations": ["运用穿透式审计破解看病贵难题"], "regulations": [], "keywords": ["穿透式审计", "看病贵", "医药审计", "社保民生"]},
    129: {"scene": "社保民生审计", "findings": ["健康养老服务需求持续增长"], "recommendations": ["审计助力医养结合服务优化"], "regulations": [], "keywords": ["医养结合", "养老", "审计监督", "社保民生"]},
    130: {"scene": "社保民生审计", "findings": [], "recommendations": ["从保障安全、促进公平、优化治理等维度发挥社保基金审计作用"], "regulations": [], "keywords": ["社保基金", "审计", "共同富裕", "民生审计"]},
    131: {"scene": "社保民生审计", "findings": ["托育服务存在供需矛盾"], "recommendations": ["推动托育服务质量齐升"], "regulations": [], "keywords": ["托育服务", "审计调研", "社保民生", "生育支持"]},
    132: {"scene": "经济责任审计", "findings": [], "recommendations": ["以五个三工作机制科学规范提升经济责任审计质效"], "regulations": [], "keywords": ["经济责任审计", "五个三", "金华", "科学规范"]},
    133: {"scene": "经济责任审计", "findings": [], "recommendations": ["以党的二十届四中全会精神为指引推动十五五经责审计工作高质量发展"], "regulations": [], "keywords": ["经济责任审计", "河北", "十五五", "高质量发展"]},
    134: {"scene": "经济责任审计", "findings": [], "recommendations": ["深化经济责任审计实践与探索"], "regulations": [], "keywords": ["经济责任审计", "东营", "黄河流域", "实践探索"]},
    135: {"scene": "经济责任审计", "findings": [], "recommendations": ["以正确政绩观引领经济责任审计"], "regulations": [], "keywords": ["经济责任审计", "湖南", "正确政绩观", "审计保障"]},
    136: {"scene": "经济责任审计", "findings": [], "recommendations": ["开展公安机关主要领导干部经济责任审计实务探究"], "regulations": [], "keywords": ["公安机关", "经济责任审计", "领导干部", "实务方法"]},
    137: {"scene": "经济责任审计", "findings": ["公立医院经责审计评价尚未形成统一公认的评价模式"], "recommendations": ["构建公立医院经责审计评价指标体系"], "regulations": ["《党政主要领导干部和国有企事业单位主要领导人员经济责任审计规定》"], "keywords": ["公立医院", "经济责任审计", "审计评价", "指标体系"]},
    138: {"scene": "经济责任审计", "findings": [], "recommendations": ["创新规范提质效推动浙江十五五经责审计高质量发展"], "regulations": [], "keywords": ["经济责任审计", "浙江", "十五五", "创新规范"]},
    139: {"scene": "经济责任审计", "findings": [], "recommendations": ["加强闭环管控完善经济责任审计工作机制"], "regulations": [], "keywords": ["经济责任审计", "四川", "闭环管控", "工作机制"]},
    140: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["经济责任审计", "周至县", "党政领导干部", "审计实践"]},
    141: {"scene": "经济责任审计", "findings": ["国企经责审计中财务收支审计质效有待提升"], "recommendations": ["提升国企经责审计中有关财务收支情况的审计质效"], "regulations": ["《党政主要领导干部和国有企事业单位主要领导人员经济责任审计规定》"], "keywords": ["国有企业", "经济责任审计", "财务收支", "审计质效"]},
    142: {"scene": "经济责任审计", "findings": [], "recommendations": ["结合研究型审计理念开展基础教育学校经责审计"], "regulations": [], "keywords": ["基础教育", "学校审计", "经济责任审计", "研究型审计"]},
    143: {"scene": "经济责任审计", "findings": [], "recommendations": ["完善经济责任审计体系，创新提升监督效能"], "regulations": ["《党政主要领导干部和国有企事业单位主要领导人员经济责任审计规定》"], "keywords": ["中国海油", "经济责任审计", "央企", "实践探索"]},
    144: {"scene": "经济责任审计", "findings": ["传统审计模式在应对复杂经济政策和市场环境时面临诸多挑战"], "recommendations": ["强化财务共享创新国有建筑企业内部管理领导人员经济责任审计"], "regulations": [], "keywords": ["国有建筑企业", "经济责任审计", "财务共享", "审计创新"]},
    145: {"scene": "经济责任审计", "findings": [], "recommendations": ["把握历史机遇强化使命担当推动黑龙江十五五经责审计工作"], "regulations": [], "keywords": ["黑龙江", "经济责任审计", "十五五", "审计使命"]},
    146: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["河南", "经济责任审计", "十四五回顾", "审计改革"]},
    147: {"scene": "经济责任审计", "findings": [], "recommendations": ["关注文旅部门主要领导干部经济责任审计实务要点"], "regulations": ["《非物质文化遗产法》", "《国家非物质文化遗产保护专项资金管理办法》"], "keywords": ["文化和旅游", "经济责任审计", "实务要点", "领导干部"]},
    148: {"scene": "经济责任审计", "findings": [], "recommendations": ["深化经济责任审计锻造规范权力运行的审计利剑"], "regulations": [], "keywords": ["安徽", "经济责任审计", "十四五回顾", "权力监督"]},
    149: {"scene": "经济责任审计", "findings": [], "recommendations": ["以研究型审计赋能国企高质量发展"], "regulations": [], "keywords": ["研究型审计", "经济责任审计", "兰溪", "国企审计"]},
    150: {"scene": "经济责任审计", "findings": [], "recommendations": ["重视经济责任审计证据质量"], "regulations": [], "keywords": ["经济责任审计", "审计证据", "取证方法"]},
    151: {"scene": "经济责任审计", "findings": [], "recommendations": ["按证明目的对经责审计证据进行分类收集"], "regulations": [], "keywords": ["经济责任审计", "审计证据", "证据分类", "取证思路"]},
    152: {"scene": "经济责任审计", "findings": ["县级审计机关面对基层单位职能交叉、业务复杂"], "recommendations": ["高质量编制综合行政执法局经责审计实施方案"], "regulations": [], "keywords": ["综合行政执法", "经济责任审计", "实施方案", "县级审计"]},
    153: {"scene": "经济责任审计", "findings": [], "recommendations": ["构建能源类国企经责审计评价指标体系"], "regulations": [], "keywords": ["能源国企", "经济责任审计", "评价指标", "层次分析法"]},
    154: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["广东", "经济责任审计", "十五五", "审计担当"]},
    155: {"scene": "经济责任审计", "findings": [], "recommendations": ["围绕行政事业单位职能职责和干部履职特点开展经责审计"], "regulations": [], "keywords": ["行政事业单位", "经济责任审计", "重点内容", "履职特点"]},
    156: {"scene": "经济责任审计", "findings": [], "recommendations": ["发挥经责审计在推进党的自我革命中的独特作用"], "regulations": [], "keywords": ["经济责任审计", "自我革命", "一把手监督", "审计地位"]},
    157: {"scene": "经济责任审计", "findings": [], "recommendations": ["构建经济责任审计1+N制度矩阵"], "regulations": [], "keywords": ["云南", "经济责任审计", "制度矩阵", "十五五"]},
    158: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["全面从严治党", "第一责任人", "领导干部职责", "经济责任审计"]},
    159: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["安全生产", "第一责任人", "领导干部职责", "经济责任审计"]},
    160: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["法治建设", "第一责任人", "领导干部职责", "经济责任审计"]},
    161: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["管理监督", "领导干部职责", "经济责任审计", "履职要求"]},
    162: {"scene": "经济责任审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["发展规划", "领导干部职责", "经济责任审计", "履职要求"]},
    163: {"scene": "经济责任审计", "findings": [], "recommendations": ["关注高校主要领导人员经济责任审计重点内容"], "regulations": [], "keywords": ["高校", "经济责任审计", "重点内容", "领导干部"]},
    164: {"scene": "资源环境审计", "findings": ["ESG鉴证面临保证程度提升困境"], "recommendations": ["提升ESG鉴证保证程度的对策"], "regulations": [], "keywords": ["ESG", "鉴证", "可持续发展", "环境审计"]},
    165: {"scene": "资源环境审计", "findings": [], "recommendations": ["以高质量审计监督护航绿色低碳循环经济发展"], "regulations": [], "keywords": ["绿色低碳", "循环经济", "资源循环", "审计监督"]},
    166: {"scene": "资源环境审计", "findings": [], "recommendations": ["协同推进降碳减污扩绿增长共建能源转型"], "regulations": [], "keywords": ["降碳减污", "能源转型", "电力行业", "绿色发展", "资源环境审计"]},
    167: {"scene": "资源环境审计", "findings": ["地热资源开发可能引发地面沉降、地温变化等问题"], "recommendations": ["运用地理信息技术审查地热井设置合规性"], "regulations": [], "keywords": ["地热井", "地理信息", "资源环境审计", "合规性审查"]},
    168: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": ["审计文博", "大思政课", "审计教育", "文化资源"]},
    169: {"scene": "资源环境审计", "findings": ["海洋生态保护修复政策落实存在政治站位、部门统筹、生态红线、资金管理等方面梗阻"], "recommendations": ["强化政治引领与战略协同", "深化审计监督与资金绩效管理"], "regulations": [], "keywords": ["海洋生态", "保护修复", "政策措施", "审计监督"]},
    170: {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": ["《中华人民共和国生态环境法典》"], "keywords": ["生态文明", "生态环境法典", "卷首语"]},
    171: {"scene": "资源环境审计", "findings": ["海域开发利用、海洋生态监管、监测等方面存在影响海洋生态可持续发展的问题"], "recommendations": ["重点关注政策规划统一性、海域空间管控科学性、海洋保护地政策落实等方面"], "regulations": [], "keywords": ["海洋生态", "保护修复", "审计关注", "生态文明建设"]},
    172: {"scene": "资源环境审计", "findings": ["采矿权管理不规范、资源利用效率低、生态破坏修复不到位"], "recommendations": ["运用卫星遥感、无人机航拍等新技术开展矿产资源审计"], "regulations": [], "keywords": ["矿产资源", "开发利用", "专项审计", "卫星遥感", "生态修复"]},
    173: {"scene": "金融审计", "findings": ["供应链金融等跨业务链条审计面临数据来源分散、结构差异显著等问题"], "recommendations": ["运用AI赋能跨业务链条审计风险识别"], "regulations": [], "keywords": ["商业银行", "跨业务链条", "审计风险", "供应链金融"]},
    174: {"scene": "金融审计", "findings": [], "recommendations": ["加强国家审计对绿色金融的监督作用"], "regulations": [], "keywords": ["绿色金融", "国家审计", "研究现状", "金融审计"]},
    175: {"scene": "金融审计", "findings": ["财产保险行业审计面临风险预警能力不足问题"], "recommendations": ["构建基于审计风险画像和AI大模型的智能审计监督体系"], "regulations": [], "keywords": ["保险审计", "风险画像", "AI大模型", "智能审计", "财产保险"]},
    176: {"scene": "社保民生审计", "findings": ["工伤保险基金面临制度复杂、信息孤岛及欺诈风险"], "recommendations": ["构建基于大数据的三维全周期审计模式"], "regulations": [], "keywords": ["工伤保险", "基金审计", "大数据", "社保民生", "全周期审计"]},
    177: {"scene": "金融审计", "findings": ["政府专项债券存在新增限额分配不合理、资金使用效益不高等问题"], "recommendations": ["构建数智化政府专项债券审计路径"], "regulations": [], "keywords": ["政府专项债券", "数智化审计", "债务审计", "金融审计"]},
    178: {"scene": "金融审计", "findings": ["财产保险公司内部审计面临样本代表性不足、非结构化数据大量存在等问题"], "recommendations": ["推进财产保险公司内部审计数字化创新"], "regulations": [], "keywords": ["财产保险", "内部审计", "数字化", "金融审计"]},
    179: {"scene": "金融审计", "findings": ["商业银行内部审计存在审计计划制定不规范、制度梳理不全面等问题"], "recommendations": ["运用人工智能技术提升商业银行内部审计规范性"], "regulations": [], "keywords": ["商业银行", "内部审计", "人工智能", "规范性", "金融审计"]},
    180: {"scene": "金融审计", "findings": ["金融服务乡村振兴缺乏审计评价的体系和标准"], "recommendations": ["构建金融服务乡村振兴审计评价体系"], "regulations": [], "keywords": ["金融服务", "乡村振兴", "审计评价", "商业银行", "金融审计"]},
}

# 按原始顺序构建输出
results = []
for item in data:
    fid = item['id']
    cls = CLASSIFICATIONS.get(fid, {"scene": "其他审计", "findings": [], "recommendations": [], "regulations": [], "keywords": []})
    results.append({
        "filepath": item['filepath'],
        "filename": item['filename'],
        "scene": cls["scene"],
        "findings": cls["findings"],
        "recommendations": cls["recommendations"],
        "regulations": cls["regulations"],
        "keywords": cls["keywords"]
    })

out_path = r'D:\openclaw-workspace\scripts\classification_results.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=1)

# 统计场景分布
from collections import Counter
scenes = Counter(r['scene'] for r in results)
print(f"分类完成，共处理{len(results)}个文件")
print(f"\n各场景分布:")
for scene, count in scenes.most_common():
    print(f"  {scene}: {count}篇")
print(f"\n结果已保存至: {out_path}")
